# ===============================================================
# Redefine 主题自定义配置
# ===============================================================

# 1. 基础信息设置
info:
  title: Hexo-haohao3001小站 # 您的博客标题
  author: haohao3001       # 作者名字

# 2. 导航栏菜单
menu:
  Home:
    path: /
    icon: fa-regular fa-house
  Archives:
    path: /archives
    icon: fa-regular fa-archive

# 3. 页脚设置
footer:
  enable: true
  # 建站年份
  since: 2026
  
  # 自定义跳动心形图标
  icon: '<i class="fa-solid fa-heart fa-beat" style="--fa-animation-duration: 0.5s; color: #ff0000"></i>'
  
  # 版权所有人
  copyright: haohao3001
  
  # 是否显示 "Powered by Hexo & Redefine"（设为 false 可获得最干净的页脚）
  powered: true
  
  # 是否显示建站时间计时（设为 false 不会显示博客运行了多少天）
  runtime: false
defaults:
  # 网站图标 (favicon)
  favicon: /images/redefine-favicon.svg
  
  # 您的头像
  avatar: 'https://github.com/haohao3001.png'